version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: cli_livre
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db
  redisdb:
      image: redis:7.0
      container_name: redisdb
      restart: unless-stopped
      ports:
        - "6379:6379"
      environment:
        REDIS_HOST_USERNAME: root
        REDIS_HOST_PASSWORD: example
      volumes:
        - redis-data:/data
  cassandradb:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    volumes:
      - cassandra-data:/var/lib/cassandra

volumes:
  mongodb-data:
  redis-data:
  cassandra-data:
